export default Presentation = [
  {
    id: 1,
    page: '마이페이지',
    title: 'superbase Mapping Issue',
    beforeDesc: `답변단 글의 원글을 가져올때 로그인유저의 답변데이터는 가져왔는데, 답변한 원글의 데이터를 가져올 수 있는 연결된 데이터값이 없었다.`,
    afterDesc: `supabase에서 Comment테이블에 writerUserId(댓글 작성자)와 Post테이블의 userId를 맴핑하여 연결해준  답변글 + 해당하는 포스팅 정보를 전부 가져와 로그인유저의 아이디 기준으로 필터링 하여 노출하였다.`,
    beforeCode: `
      supabase
        .from("Comment")
        .select("*”)
    `,
    afterCode: `
      // supabase Comment 테이블 전체(*)의 연결된 Post 테이블의 모든 열(Post (*))을 선택함
      supabase
        .from("Comment")
        .select("*, Post (*)")
    `,
    img1: '',
    img2: '',
    img3: '',
    img4: '',
    img5: '',
  },
  {
    id: 2,
    title: '',
    beforeDesc: ``,
    afterDesc: ``,
    beforeCode: ``,
    afterCode: ``,
    img1: '',
    img2: '',
    img3: '',
    img4: '',
    img5: '',
  },
  {
    id: 3,
    title: '',
    beforeDesc: ``,
    afterDesc: ``,
    beforeCode: ``,
    afterCode: ``,
    img1: '',
    img2: '',
    img3: '',
    img4: '',
    img5: '',
  },
  {
    id: 4,
    title: '',
    beforeDesc: ``,
    afterDesc: ``,
    beforeCode: ``,
    afterCode: ``,
    img1: '',
    img2: '',
    img3: '',
    img4: '',
    img5: '',
  },
  {
    id: 5,
    title: '',
    beforeDesc: ``,
    afterDesc: ``,
    beforeCode: ``,
    afterCode: ``,
    img1: '',
    img2: '',
    img3: '',
    img4: '',
    img5: '',
  },
  {
    id: 6,
    title: '',
    beforeDesc: ``,
    afterDesc: ``,
    beforeCode: ``,
    afterCode: ``,
    img1: '',
    img2: '',
    img3: '',
    img4: '',
    img5: '',
  },
  {
    id: 7,
    title: '',
    beforeDesc: ``,
    afterDesc: ``,
    beforeCode: ``,
    afterCode: ``,
    img1: '',
    img2: '',
    img3: '',
    img4: '',
    img5: '',
  },
  {
    id: 8,
    title: '',
    beforeDesc: ``,
    afterDesc: ``,
    beforeCode: ``,
    afterCode: ``,
    img1: '',
    img2: '',
    img3: '',
    img4: '',
    img5: '',
  },              
]